### ISSUE TITLE
有rime版可用的挂载文件吗

### ISSUE THREAD

**Issue by bosconb** [ledao/lufly-im#1]
这个魔改有点意思

**Comment by colawithsauce** [comment]
虽然催不太好，但是现在我非常期待作者的更新。
不然我只能奋力尝试自己做一个了，这个方案实在是太好用了

**Comment by ledao** [comment]
我自己的计划是在2019年年底前推出rime版本，目前东家的项目正在关键时期，有点脱不开身。

**Comment by bosconb** [comment]
感谢！期待！

**Comment by Wang-Yibin** [comment]
感谢作者的作品，跪求rime版本  ！

**Comment by ledao** [comment]
rime版本已出，请下载1.4.0版本

**Comment by ledao** [comment]
https://zhuanlan.zhihu.com/p/112280054

**Comment by ledao** [comment]
https://zhuanlan.zhihu.com/p/112280054
rime版本，请下载1.4.0版本

**Comment by TTTPOB** [comment]
已经出啦，我觉得比原版好用
