### ISSUE TITLE
键盘方案

### ISSUE THREAD

**Issue by Tunging** [ledao/lufly-im#2]
1.2.1 的小鹤双拼方案是修改过的吧
能不能提供个没经过修改的
v 原来是只有ui
现在多加了 uo 和 o键重复了

**Comment by ledao** [comment]
你好，能描述的详细一些么？

**Comment by Tunging** [comment]
不好意思，是我搞错了，那个字是多音字，只是另外一个音不常用，给列到了最前面，暂时懵逼了一下； 例如 uv ，原本是想打 “睡” ， 结果出了个 ”说“，其实也没多大问题
