### ISSUE TITLE
有些词语上屏之后最后一个字母会留在输入框里

### ISSUE THREAD

**Issue by proItheus** [ledao/lufly-im#6]
比如输入“物理”的时候词语上屏之后后面会留一个“l“，但是”屋里“就没有这种问题。类似的还有”试试“会留个"g"，可能还有更多我没发现。

**Comment by ledao** [comment]
能否上传个截图看看

**Comment by ledao** [comment]
请问，还能得到您的反馈么@[proItheus](https://github.com/proItheus)

**Comment by proItheus** [comment]
抱歉，之后突然就不能复现了，可能是我电脑的问题。本来想关闭issue的，但是忘掉了
