### ISSUE TITLE
能够提供导入现有小鹤输入法的词汇码表

### ISSUE THREAD

**Issue by jinboowu** [ledao/lufly-im#8]
用了下，基本上和当前的小鹤输入法之间没什么冲突，但是一些快捷输入方式和功能（比如说查字）没有感觉有点不方便，如果能够提供词汇表的话，直接导入到现有的小鹤输入法，就比较完美了

**Comment by ledao** [comment]
快捷输入：我理解是简码输入，目前支持的简码很少；
查字：此功能确实是没有，后续会逐渐添加。
码表的获取渠道：
1. 本仓库的根目录下的：/dd_**  /rime_**，即为多多和rime可用的码表、配置文件，可直接使用。
2. 加入群，在群里直接找群主要最新的。
